In [1]:
import pandas as pd
import numpy as np

In [2]:
CR7 = pd.read_csv("CR7data.csv")
CR7_pen = pd.read_csv("CR7penalties.csv")
# importing Cristiano Ronaldo club goals & Penalty goals data from .csv files from Kaggle.

In [3]:
CR7.head()
# show first few rows of the dataset

,Unnamed: 0,Goal_no,Season,Competition,Matchday,Venue,Team,Opponent,Result,Position,Minute,At_score,Type_of_goal
0,0,1,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,LW,34,2:0,Solo run
1,1,2,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,NaN,90+5,3:0,Header
2,2,3,2/3,Liga Portugal,8,A,Sporting CP,Boavista FC,1:2,NaN,88,1:2,Right-footed shot
3,3,4,2/3,TaÃ§a de Portugal Placard,Fourth Round,H,Sporting CP,CD Estarreja,4:1,NaN,67,3:0,Left-footed shot
4,4,5,2/3,TaÃ§a de Portugal Placard,Fifth Round,H,Sporting CP,FC Oliveira do Hospital,8:1,NaN,13,3:0,NaN

In [4]:
CR7.info()
# return the information types of each column - also check for any missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    698 non-null    int64
 1   Goal_no       698 non-null    int64
 2   Season        698 non-null    object
 3   Competition   698 non-null    object
 4   Matchday      698 non-null    object
 5   Venue         698 non-null    object
 6   Team          698 non-null    object
 7   Opponent      698 non-null    object
 8   Result        698 non-null    object
 9   Position      640 non-null    object
 10  Minute        698 non-null    object
 11  At_score      698 non-null    object
 12  Type_of_goal  683 non-null    object
dtypes: int64(2), object(11)
memory usage: 71.0+ KB

In [5]:
# so it's a dataframe with 698 rows & 13 columns
# two columns have missing values, so hopefully only minor cleaning required

In [6]:
CR7.isnull().sum()

Unnamed: 0       0
Goal_no          0
Season           0
Competition      0
Matchday         0
Venue            0
Team             0
Opponent         0
Result           0
Position        58
Minute           0
At_score         0
Type_of_goal    15
dtype: int64

In [18]:
missing_values = CR7['Position'].isnull().sum()
missing_values

58

In [19]:
total_rows = CR7.shape[0]
total_rows

698

In [20]:
percentNA = (missing_values / total_rows) * 100
percentNA

8.30945558739255

In [21]:
def size_NA(df, name):                 # Here we take in the dataframe & column name, represented by "df" & "name"
    missing_values = df[name].isnull().sum()  # assign the number of null cells in the column to missing_values
    total_rows = df.shape[0]                 # assign the number of rows in the dataframe to total_rows
    percentNA = (missing_values / total_rows) * 100 # assign the % of rows in the df that contain null values to percentNA
    return percentNA       # And now we return this function as the variable "percentNA"

In [22]:
size_NA(CR7,'Position')

8.30945558739255

In [23]:
# based on this I wouldn't loose a significant amount of data by doing a drop NA.

In [24]:
drop_duplicates= CR7.drop_duplicates() # perform drop duplicates on CR7 & dave in drop duplicates
print(CR7.shape,drop_duplicates.shape) # print the shape of CR7 & drop duplicates

(698, 13) (698, 13)

In [25]:
# so no duplicates in our dataframe

In [33]:
CR7['# of Goals']=1
# add a column of 1s into the DF so I can perform sum, mean,etc. calculations on the data
CR7

,Unnamed: 0,Goal_no,Season,Competition,Matchday,Venue,Team,Opponent,Result,Position,Minute,At_score,Type_of_goal,# of Goals
0,0,1,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,LW,34,2:0,Solo run,1
1,1,2,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,NaN,90+5,3:0,Header,1
2,2,3,2/3,Liga Portugal,8,A,Sporting CP,Boavista FC,1:2,NaN,88,1:2,Right-footed shot,1
3,3,4,2/3,TaÃ§a de Portugal Placard,Fourth Round,H,Sporting CP,CD Estarreja,4:1,NaN,67,3:0,Left-footed shot,1
4,4,5,2/3,TaÃ§a de Portugal Placard,Fifth Round,H,Sporting CP,FC Oliveira do Hospital,8:1,NaN,13,3:0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,693,694,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,32,2:0,Header,1
694,694,695,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,76,3:2,Direct free kick,1
695,695,696,21/22,Premier League,34,A,Manchester United,Arsenal FC,3:1,CF,34,2:1,Left-footed shot,1
696,696,697,21/22,Premier League,37,H,Manchester United,Chelsea FC,1:1,CF,62,1:1,Right-footed shot,1
697,697,698,21/22,Premier League,35,H,Manchester United,Brentford FC,3:0,CF,61,2:0,Penalty,1

In [37]:
CR7_idx = CR7.set_index('Goal_no') # set index to the Goal number

In [38]:
CR7_idx

,Unnamed: 0,Season,Competition,Matchday,Venue,Team,Opponent,Result,Position,Minute,At_score,Type_of_goal,# of Goals
Goal_no,,,,,,,,,,,,,
1,0,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,LW,34,2:0,Solo run,1
2,1,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,NaN,90+5,3:0,Header,1
3,2,2/3,Liga Portugal,8,A,Sporting CP,Boavista FC,1:2,NaN,88,1:2,Right-footed shot,1
4,3,2/3,TaÃ§a de Portugal Placard,Fourth Round,H,Sporting CP,CD Estarreja,4:1,NaN,67,3:0,Left-footed shot,1
5,4,2/3,TaÃ§a de Portugal Placard,Fifth Round,H,Sporting CP,FC Oliveira do Hospital,8:1,NaN,13,3:0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,693,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,32,2:0,Header,1
695,694,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,76,3:2,Direct free kick,1
696,695,21/22,Premier League,34,A,Manchester United,Arsenal FC,3:1,CF,34,2:1,Left-footed shot,1
697,696,21/22,Premier League,37,H,Manchester United,Chelsea FC,1:1,CF,62,1:1,Right-footed shot,1
698,697,21/22,Premier League,35,H,Manchester United,Brentford FC,3:0,CF,61,2:0,Penalty,1

In [40]:
CR7_idx.drop('Unnamed: 0', axis=1, inplace=True) # remove the Unnamed column
CR7_idx # print the indexed DF

,Season,Competition,Matchday,Venue,Team,Opponent,Result,Position,Minute,At_score,Type_of_goal,# of Goals
Goal_no,,,,,,,,,,,,
1,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,LW,34,2:0,Solo run,1
2,2/3,Liga Portugal,6,H,Sporting CP,Moreirense FC,3:0,NaN,90+5,3:0,Header,1
3,2/3,Liga Portugal,8,A,Sporting CP,Boavista FC,1:2,NaN,88,1:2,Right-footed shot,1
4,2/3,TaÃ§a de Portugal Placard,Fourth Round,H,Sporting CP,CD Estarreja,4:1,NaN,67,3:0,Left-footed shot,1
5,2/3,TaÃ§a de Portugal Placard,Fifth Round,H,Sporting CP,FC Oliveira do Hospital,8:1,NaN,13,3:0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
694,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,32,2:0,Header,1
695,21/22,Premier League,33,H,Manchester United,Norwich City,3:2,CF,76,3:2,Direct free kick,1
696,21/22,Premier League,34,A,Manchester United,Arsenal FC,3:1,CF,34,2:1,Left-footed shot,1
697,21/22,Premier League,37,H,Manchester United,Chelsea FC,1:1,CF,62,1:1,Right-footed shot,1
698,21/22,Premier League,35,H,Manchester United,Brentford FC,3:0,CF,61,2:0,Penalty,1